# FROM python:3.9.1

# RUN apt-get install wget
# RUN pip install pandas sqlalchemy psycopg2

# WORKDIR /app
# COPY green_zone_ingest.py green_zone_ingest.py 

# ENTRYPOINT [ "python", "green_zone_ingest.py" ]

FROM python:3.9

ENTRYPOINT ["bash"]